"""Console-script entry for ``superclaude`` (pyproject ``[project.scripts]``).

``superclaude hook <name>`` — the form every hooks.json registration takes —
is dispatched to ``hook_dispatch`` before the click application is imported;
that module's docstring carries the why and the measurements. Everything else
goes to the click group in ``main.py``, which also registers ``hook`` for the
``--help`` listing and for a console script generated by a previous release
(whose shim still imports ``superclaude.cli.main:main``).
"""

from __future__ import annotations

import os
import sys


def main() -> int:
    # The interpreter puts the console script's own directory first on
    # sys.path. For `~/.local/bin/superclaude` that is a general-purpose user bin
    # shared with uv, pipx and the user's own scripts, so a stray `json.py` or
    # `re.py` there would shadow the stdlib for every hook. The previous form
    # ran from a directory SuperClaude owned; dropping the entry keeps that.
    if sys.argv and sys.argv[0] and os.path.isfile(sys.argv[0]):
        script_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
        if sys.path and os.path.abspath(sys.path[0] or os.curdir) == script_dir:
            del sys.path[0]

    argv = sys.argv[1:]
    if argv and argv[0] == "hook":
        from .hook_dispatch import run_hook

        return run_hook(argv[1:])

    from .main import main as cli

    return cli()
