"""Console-script entry for ``superclaude`` (pyproject ``[project.scripts]``).

One entry, two paths. ``superclaude hook <name>`` — the form every hooks.json
registration takes — is dispatched to ``hook_dispatch`` before the click
application is imported, because that import alone (~40ms for click + yaml,
measured 2026-09-05) costs more than a whole hook run (~20ms) and hooks fire
three times per Bash tool call. Everything else goes to the click group in
``main.py``, which also registers ``hook`` so ``superclaude --help`` lists it
and a console script generated by a previous release (whose shim still imports
``superclaude.cli.main:main``) keeps working, just without the fast path.
"""

from __future__ import annotations

import sys


def main() -> int:
    argv = sys.argv[1:]
    if argv and argv[0] == "hook":
        from .hook_dispatch import run_hook

        return run_hook(argv[1:])

    from .main import main as cli

    return cli()
